import StyleDictionary from 'style-dictionary';
import { typographySplitParser } from './src/dictionary/parser.js'
import transforms from './src/dictionary/transforms.js';
import groups from './src/dictionary/transformGroups.js';
import formats from './src/dictionary/formats.js';
import { validateTokens } from './src/dictionary/actions.js'

const HIDDEN_PRIMITIVES = ['tokens/primitives/color.tokens.json', 'tokens/primitives/type.tokens.json'];
const PRIMITIVES = [
  'tokens/primitives/borderWidth.tokens.json',
  'tokens/primitives/breakpoints.tokens.json',
  'tokens/primitives/opacity.tokens.json',
  'tokens/primitives/radius.tokens.json',
  'tokens/primitives/shadow.tokens.json',
  'tokens/primitives/spacing.tokens.json',
  'tokens/primitives/zIndex.tokens.json'
];
const SEMANTICS = ['tokens/semantic/**/*.tokens.json'];

const buildDictionary = async () => {
  const hooks = {
    transforms: Object.fromEntries(transforms.map((t) => [t.name, t])),
    formats: Object.fromEntries(formats.map((f) => [f.name, f.format])),
    transformGroups: Object.fromEntries(groups.map((g) => [g.name, g.transforms])),
    actions: { [validateTokens.name]: validateTokens },
    parsers: {
      'typography-split': typographySplitParser,
    },
    fileHeaders: {
      'qm-header': () => [`generated by @quartermaster/ui-tokens, do not edit`]
    }
  }

  // Base token build for CSS - include typography parser to surface letterSpacing variables
  const sdDefaultCss = new StyleDictionary({
    log: { verbosity: 'verbose'},
    usesDtcg: true,
    hooks,
    parsers: ['typography-split'],
    // Primitive type and colour tokens are in 'include' for reference, not emitted
    include: HIDDEN_PRIMITIVES,
    source: [...PRIMITIVES, ...SEMANTICS],
    platforms: {
      // CSS: Tailwind @theme block
      css: {
        transformGroup: 'css/tokens',
        buildPath: 'dist/css/',
        actions: ['validate-tokens'],
        files: [
          {
            destination: 'tokens.css',
            filter: token => token.isSource,
            format: 'css/tailwind-theme',
            options: {
              fileHeader: 'qm-header'
            }
          },
        ],
      },
    },
  });

  // Base token build for React Native - no parser needed
  const sdDefaultNative = new StyleDictionary({
    log: { verbosity: 'verbose'},
    usesDtcg: true,
    hooks,
    include: HIDDEN_PRIMITIVES,
    source: [...PRIMITIVES, ...SEMANTICS],
    platforms: {
      // Object to be used in tailwind.config
      native: {
        transformGroup: 'json/tokens',
        buildPath: 'dist/native',
        actions: ['validate-tokens'],
        files: [
          {
            destination: 'native.ts',
            filter: token => token.isSource,
            format: 'js/tw-react-native',
            options: {
              exportName: 'baseTheme',
              fileHeader: 'qm-header',
            }
          }
        ]
      }
    },
  });

  await Promise.all([sdDefaultCss.buildAllPlatforms(), sdDefaultNative.buildAllPlatforms()]);

  // MODES BUILD
  const modes = [
    {
      name: 'pro',
      cssSelector: '[data-theme="pro"]',
      rnExportName: 'proThemeOverride',
    },
  ]

  const modeBuilds = modes.map(async (mode) => {
    // CSS override modes only need the override values to define under the given selector
    const cssMode = new StyleDictionary({
      log: {verbosity : 'verbose'},
      usesDtcg: true,
      hooks,
      parsers: ['typography-split'],
      include: [...PRIMITIVES, ...HIDDEN_PRIMITIVES, ...SEMANTICS],
      source: [`tokens/modes/${mode.name}.tokens.json`],
      platforms: {
        css: {
          transformGroup: 'css/tokens',
          buildPath: 'dist/css/',
          actions: ['validate-tokens'],
          files: [
            {
              destination: `tokens.${mode.name}.css`,
                format: 'css/variables',
                filter: (token) => token.isSource,
                options: { 
                  selector: mode.cssSelector,
                  fileHeader: 'qm-header'
                },
              },
            ],
          },
      },
    }).buildAllPlatforms();

    // Native override modes need the entire theme object, and therefoer surface default values
    // and the mode variables
    const nativeMode = new StyleDictionary({
      usesDtcg: true,
      hooks,
      include: [...HIDDEN_PRIMITIVES],
      source: [ ...PRIMITIVES, ...SEMANTICS, `tokens/modes/${mode.name}.tokens.json`],
      platforms: {
        native: {
          transformGroup: 'json/tokens',
          buildPath: 'dist/native',
          actions: ['validate-tokens'],
          files: [
            {
              destination: `native.${mode.name}.ts`,
              filter: token => token.isSource,
              format: 'js/tw-react-native',
              options: {
                exportName: `${mode.name}Theme`,
                fileHeader: 'qm-header',
              }
            }
          ]
        }
      },
    }).buildAllPlatforms();

    return Promise.all([cssMode, nativeMode])
  });
  await Promise.all(modeBuilds);
}
buildDictionary();
