import StyleDictionary from 'style-dictionary';
import { typographySplitParser } from './src/dictionary/parser.js'
import transforms from './src/dictionary/transforms.js';
import groups from './src/dictionary/transformGroups.js';
import formats from './src/dictionary/formats.js';
import { validateTokens } from './src/dictionary/actions.js'

const HIDDEN_PRIMITIVES = ['tokens/primitives/color.tokens.json', 'tokens/primitives/type.tokens.json'];
const PRIMITIVES = [
  'tokens/primitives/borderWidth.tokens.json',
  'tokens/primitives/breakpoints.tokens.json',
  'tokens/primitives/opacity.tokens.json',
  'tokens/primitives/radius.tokens.json',
  'tokens/primitives/shadow.tokens.json',
  'tokens/primitives/spacing.tokens.json',
  'tokens/primitives/zIndex.tokens.json'
];
const SEMANTICS = ['tokens/semantic/**/*.tokens.json'];

const buildDictionary = async () => {
  const hooks = {
    transforms: Object.fromEntries(transforms.map((t) => [t.name, t])),
    formats: Object.fromEntries(formats.map((f) => [f.name, f.format])),
    transformGroups: Object.fromEntries(groups.map((g) => [g.name, g.transforms])),
    actions: { [validateTokens.name]: validateTokens },
    parsers: {
      'typography-split': typographySplitParser,
    },
    fileHeaders: {
      'qm-header': () => [`generated by @quartermaster/ui-tokens, do not edit`]
    }
  }

  // Pass 1: Base tokens → CSS + ReactNative base theme
  const sdDefault = new StyleDictionary({
    usesDtcg: true,
    hooks,
    parsers: ['typography-split'],
    // Primitive type and colour tokens are in 'include' for reference, not emitted
    include: HIDDEN_PRIMITIVES,
    source: [...PRIMITIVES, ...SEMANTICS],
    platforms: {
      // CSS: Tailwind @theme block
      css: {
        transformGroup: 'css/tokens',
        buildPath: 'dist/css/',
        actions: ['validate_tokens'],
        files: [
          {
            destination: 'tokens.css',
            filter: token => token.isSource,
            format: 'css/tailwind-theme',
            options: {
              fileHeader: 'qm-header'
            }
          },
        ],
      },
    },
  });

  await sdDefault.buildAllPlatforms();

  const modes = [
    {
      name: 'pro',
      cssSelector: '[data-theme="pro"]',
      rnExportName: 'proThemeOverride',
    },
  ]

  const buildMode = modes.map(async (mode) => {
    const sdMode = new StyleDictionary({
      usesDtcg: true,
      hooks,
      parsers: ['typography-split'],
      include: [...PRIMITIVES, ...HIDDEN_PRIMITIVES, ...SEMANTICS],
      // Only the mode file is "source" — only these tokens are emitted
      source: [`tokens/modes/${mode.name}.tokens.json`],
      platforms: {
        css: {
          transformGroup: 'css/tokens',
          buildPath: 'dist/css/',
          actions: ['validate_tokens'],
          files: [
            {
              destination: `tokens.${mode.name}.css`,
              format: 'css/variables',
              filter: (token) => token.isSource,
              options: { 
                selector: mode.cssSelector,
                fileHeader: 'qm-header'
              },
            },
          ],
        },
      },
    });
    return sdMode.buildAllPlatforms();
  })

  await Promise.all(buildMode);
}
buildDictionary();
