import { type TransformedToken, type Format, type FormatFnArguments } from 'style-dictionary/types';

// for base Tailwind @theme
export const tailwindTheme: Format = {
  name: 'css/tailwind-theme',
  format: ({ dictionary, file }: FormatFnArguments) => {
    const vars = dictionary.allTokens
        .filter((token: TransformedToken) => {
          const val = token.$value ?? token.value;
          //filter out any tokens where transformation logic failed
          return val !== null && val !== undefined && typeof val !== 'object'
        })
        .map((token: TransformedToken) => {
          let val = token.$value ?? token.value;
          if (typeof val === 'string' && val[val.length - 1] === ';') {
            val = val.slice(0, -1);
          }
          return `  --${token.name}: ${val};`
        })
        .join('\n');

    if (!vars.trim()) {
      return `/* No tokens found for ${file.destination} */`
    }

    return [
      '/* GENERATED by @quartermaster/ui-tokens */',
      '@theme {',
      '  --color-*: initial;',
      '  --spacing-*: initial;',
      '  --radius-*: initial;',
      '}',
      '',
      '@theme {',
      vars,
      '}',
    ].join('\n');
  },
};

// for css override with [data-theme="mode"]
export const cssOverride: Format = {
  name: 'css/override',
  format: ({ dictionary, options, file }: FormatFnArguments) => {
    const selector = options?.selector ?? ':root';
    const vars = dictionary.allTokens
      .filter((token: TransformedToken) => {
        const val = token.$value ?? token.value;
        return val !== null && val !== undefined && typeof val !== 'object'
      })
      .map((token: TransformedToken) => {
        let val = token.$value ?? token.value;
        if (typeof val === 'string' && val[val.length - 1] === ';') {
          val = val.slice(0, -1);
        }
        return `  --${token.name}: ${val};`
      })
      .join('\n');

    if (!vars.trim()) {
      return `/* No tokens found for ${file.destination} */`
    }

    return [
      '/* GENERATED by @quartermaster/ui-tokens — do not edit by hand */',
      `${selector} {`,
      vars,
      '}',
      '',
    ].join('\n');
  },
};

const formats = [tailwindTheme, cssOverride];
export default formats;