import StyleDictionary from 'style-dictionary';
import type { TransformedToken, Config } from 'style-dictionary/types';
import transforms from './dictionary/transforms.js';
import groups from './dictionary/transformGroups.js';
import formats from './dictionary/formats.js';
import { validateTokens } from './dictionary/actions.js';

const HIDDEN_PRIMITIVES = [
  'tokens/primitives/color.tokens.json',
  'tokens/primitives/type.tokens.json',
];
const PRIMITIVES = [
  'tokens/primitives/borderWidth.tokens.json',
  'tokens/primitives/breakpoints.tokens.json',
  'tokens/primitives/opacity.tokens.json',
  'tokens/primitives/radius.tokens.json',
  'tokens/primitives/spacing.tokens.json',
  'tokens/primitives/zIndex.tokens.json',
];
const SEMANTICS = ['tokens/semantic/**/*.tokens.json'];
const CSS_SHADOW = 'tokens/primitives/shadow.tokens.json';
const NATIVE_SHADOW = 'tokens/primitives/shadowNative.tokens.json';

type modeType = {
  name: string;
  cssSelector: string;
  rnExportName: string;
};

const buildDictionary = async () => {
  const hooks = {
    transforms: Object.fromEntries(transforms.map((t) => [t.name, t])),
    formats: Object.fromEntries(formats.map((f) => [f.name, f.format])),
    transformGroups: Object.fromEntries(
      groups.map((g) => [g.name, g.transforms]),
    ),
    actions: { [validateTokens.name]: validateTokens },
    fileHeaders: {
      'qm-header': () => [
        `generated by @Quartermaster-Inc/qm-tokens, do not edit`,
      ],
    },
  };

  // Token build for CSS
  const getCssConfig = (mode?: modeType): Config => ({
    log: { verbosity: 'silent' },
    usesDtcg: true,
    hooks,
    // Include tokens are for reference, not emitted
    include: mode
      ? [...PRIMITIVES, ...HIDDEN_PRIMITIVES, ...SEMANTICS, CSS_SHADOW]
      : HIDDEN_PRIMITIVES,
    // For override mode, only needs to surface override values for selector
    // Default @theme block renders all variables
    source: mode
      ? [`tokens/modes/${mode.name}.tokens.json`]
      : [...PRIMITIVES, ...SEMANTICS, CSS_SHADOW],
    platforms: {
      css: {
        transformGroup: 'css/tokens',
        buildPath: 'dist/css/',
        actions: ['validate-tokens'],
        files: [
          {
            destination: `tokens.${mode ? mode.name + '.' : ''}css`,
            format: mode ? 'css/variables' : 'css/tailwind-theme',
            filter: (token: TransformedToken) => token.isSource,
            options: {
              fileHeader: 'qm-header',
              selector: mode?.cssSelector,
            },
          },
          // JSON output only needs key / token names to feed into extendTailwindMerge, not token
          // values, so no need to call for base build. Include under Css Config to ensure same transforms / actions
          // are applied to both files
          ...(!mode
            ? [
                {
                  destination: '../json/tokenKeys.ts',
                  format: 'json/tw-merge',
                  filter: (token: TransformedToken) => token.isSource,
                  options: { fileHeader: 'qm-header' },
                },
              ]
            : []),
        ],
      },
    },
  });

  // Token build for RN
  const getNativeConfig = (mode?: modeType): Config => ({
    // Style Dictionary complains about too many tokens ending in 'foreground', or variables
    // being overridden by the pro mode. As these are design choices, silence the warnings.
    log: { verbosity: 'silent' },
    usesDtcg: true,
    hooks,
    include: HIDDEN_PRIMITIVES,
    source: [
      ...PRIMITIVES,
      ...SEMANTICS,
      NATIVE_SHADOW,
      mode ? `tokens/modes/${mode.name}.tokens.json` : '',
    ],
    platforms: {
      // Object to be used in TWRNC create()
      native: {
        transformGroup: 'json/tokens',
        buildPath: 'dist/native/',
        actions: ['validate-tokens'],
        files: [
          {
            destination: `native.${mode ? mode.name + '.' : ''}ts`,
            format: 'js/tw-react-native',
            filter: (token: TransformedToken) => token.isSource,
            options: {
              fileHeader: 'qm-header',
            },
          },
        ],
      },
    },
  });

  const modes = [
    {
      name: 'pro',
      cssSelector: '[data-theme="pro"]',
      rnExportName: 'proThemeOverride',
    },
  ];

  const builds = [
    // base builds
    getCssConfig(),
    getNativeConfig(),

    // mode overrides
    ...modes.map((mode) => getCssConfig(mode)),
    ...modes.map((mode) => getNativeConfig(mode)),
  ];

  await Promise.all(
    builds.map((config) => new StyleDictionary(config).buildAllPlatforms()),
  );
};
buildDictionary();
