import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import StyleDictionary from 'style-dictionary';
import type { TransformedToken, Config } from 'style-dictionary/types';
import transforms from './dictionary/transforms.js';
import groups from './dictionary/transformGroups.js';
import formats from './dictionary/formats.js';
import { validateTokens } from './dictionary/actions.js';
import { buildDtcgTrees } from './build-tree/buildTokenTree.js';
import {
  getExposure,
  shouldEmit,
  tokensFor,
} from './utilities/dictionary-helpers.js';
import type { FigmaExport } from './build-tree/types.js';

type modeType = {
  name: string;
  cssSelector: string;
  rnExportName: string;
};

const parseFigmaFile = (path: string): FigmaExport => {
  try {
    return JSON.parse(readFileSync(path, 'utf-8'));
  } catch {
    throw new Error(`Could not retrieve or parse file at ${path}`);
  }
};

// ------- Style Dictionary Builds -------

const buildDictionary = async () => {
  const tokenFilePath = resolve(
    import.meta.dirname,
    '../../tokens/figma-tokens.json',
  );
  const parsedExport = parseFigmaFile(tokenFilePath);

  const { base, modes: modeTrees } = buildDtcgTrees(parsedExport);

  const hooks = {
    transforms: Object.fromEntries(transforms.map((t) => [t.name, t])),
    formats: Object.fromEntries(formats.map((f) => [f.name, f.format])),
    transformGroups: Object.fromEntries(
      groups.map((g) => [g.name, g.transforms]),
    ),
    actions: { [validateTokens.name]: validateTokens },
    fileHeaders: {
      'qm-header': () => [`generated by @pespes/qm-tokens, do not edit`],
    },
  };

  // Token build for CSS
  const getCssConfig = (mode?: modeType): Config => ({
    log: { verbosity: 'silent' },
    usesDtcg: true,
    hooks,
    tokens: tokensFor(base, modeTrees, mode),
    platforms: {
      css: {
        transformGroup: 'css/tokens',
        buildPath: 'dist/css/',
        actions: ['validate-tokens'],
        files: [
          {
            destination: `tokens.${mode ? mode.name + '.' : ''}css`,
            format: mode ? 'css/variables' : 'css/tailwind-theme',
            // Base build emits every published token; a mode build emits only
            // the tokens that mode actually overrides.
            filter: (token: TransformedToken) =>
              mode
                ? getExposure(token).mode === mode.name
                : shouldEmit(token, 'css'),
            options: {
              fileHeader: 'qm-header',
              selector: mode?.cssSelector,
            },
          },
          // JSON output only needs key / token names to feed into extendTailwindMerge, not token
          // values, so no need to call for base build. Include under Css Config to ensure same transforms / actions
          // are applied to both files
          ...(!mode
            ? [
                {
                  destination: '../json/tokenKeys.ts',
                  format: 'json/tw-merge',
                  filter: (token: TransformedToken) => shouldEmit(token, 'css'),
                  options: { fileHeader: 'qm-header' },
                },
              ]
            : []),
        ],
      },
    },
  });

  // Token build for RN
  const getNativeConfig = (mode?: modeType): Config => ({
    // Style Dictionary complains about too many tokens ending in 'foreground', or variables
    // being overridden by the pro mode. As these are design choices, silence the warnings.
    log: { verbosity: 'silent' },
    usesDtcg: true,
    hooks,
    tokens: tokensFor(base, modeTrees, mode),
    platforms: {
      // Object to be used in TWRNC create()
      native: {
        transformGroup: 'json/tokens',
        buildPath: 'dist/native/',
        actions: ['validate-tokens'],
        files: [
          {
            destination: `native.${mode ? mode.name + '.' : ''}ts`,
            format: 'js/tw-react-native',
            // RN consumers take a whole theme object per mode instead of
            // just overriden values, so this filter ignores `mode`.
            filter: (token: TransformedToken) => shouldEmit(token, 'native'),
            options: {
              fileHeader: 'qm-header',
            },
          },
        ],
      },
    },
  });

  const modes = [
    {
      name: 'pro',
      cssSelector: '[data-theme="pro"]',
      rnExportName: 'proThemeOverride',
    },
  ];

  const builds = [
    // base builds
    getCssConfig(),
    getNativeConfig(),

    // mode overrides
    ...modes.map((mode) => getCssConfig(mode)),
    ...modes.map((mode) => getNativeConfig(mode)),
  ];

  await Promise.all(
    builds.map((config) => new StyleDictionary(config).buildAllPlatforms()),
  );
};
buildDictionary();
